### ISSUE TITLE
Tried to compile other that I and had failures

### ISSUE THREAD

**Issue by MarcKarasek** [incoresemi/riscv-compliance#4]
src/cjal-01.S:36: Error: unrecognized opcode `c.jal 3f'

All the others passed compile if you specify them individually for rv32

I removed cjal from the compile and tried to compile all of them at once by leaving RISCV_DEVICE empty in the top level Makefile.include

Both rv32 and rv64 behave the same way. they compile I, C, M but when they get to privilege it fails with the below message.  It looks like the path to the Makefile.include for the sub dir under rv32/64i_m for privilege is not getting set properly when you are compiling all. 
NOTE: If you set RISCV_DEVICE = privilege in the top level Makefile.include then it will compile.

make[2]: *** /media/marckarasek/source/incoresemi/riscv-compliance/riscv-test-suite/rv64i_m/Makefile.include: No such file or directory.  Stop.

**Comment by MarcKarasek** [comment]
The compile all is broken because of the new symlinked Makefile.include file under <target>/device/rv32i_m/ and <target>/device/rv64i_m/
The top level Makefile expects this dir to only contain RISCV_DEVICE dir and no files. 

Marc

**Comment by MarcKarasek** [comment]
Add this one line to top level Makefile line 22

RISCV_ISA_ALL := $(filter-out Makefile.include,$(RISCV_ISA_ALL))

This will fix the compile all problem. 

Will look like this after:
RISCV_ISA_ALL = $(shell ls $(TARGETDIR)/$(RISCV_TARGET)/device/rv$(XLEN)i_m)
RISCV_ISA_OPT = $(subst $(space),$(pipe),$(RISCV_ISA_ALL))

RISCV_ISA_ALL := $(filter-out Makefile.include,$(RISCV_ISA_ALL))

Marc

**Comment by MarcKarasek** [comment]
Pushed a commit to the current PR with this fix.

**Comment by MarcKarasek** [comment]
I have submitted a case to the riscv toolchain on the c.jal not recognized as an opcode. 

I will also bring this up next week at the Toolchain & Runtime TS on Thursday.

**Comment by neelgala** [comment]
can we close this ?

**Comment by MarcKarasek** [comment]
Closing this ..
